### ISSUE TITLE
How to install, set up for use by non-super user

### ISSUE THREAD

**Issue by loveencounterflow** [ChristophBerg/postgresql-unit#14]
I've managed to install the `unit` extension (reported to be version `1` in `pg_available_extension_versions`) as per my previous comment (#10) which was easy; I can then load the extension with

```sql
set role dba;
create extension unit schema public;
reset role;
```
where `dba` is a role with elevated privileges. Done that, I can now run the examples:

```sql
set role dba;
select '1 hl'::unit @ '0.5 l' AS bottles_of_beer;
reset role;
```
but **not without using superuser privileges**. How can I make it so that `unit` becomes accessible to an ordinary DB user?

**EDIT** That error was:

```
psql:db/experiments/units.sql:14: ERROR:  permission denied for relation unit_units
LINE 1: select '1 hl'::unit @ '0.5 l' AS bottles_of_beer;
```

**Comment by zr40** [comment]
Superuser isn't required, but the actual problem is that no privileges are granted on unit's internal tables, meaning only the owner (the role that created the extension) may access them.

You can execute the following as the owner or as superuser to grant these privileges to all users:

```
GRANT SELECT ON unit_units, unit_prefixes TO PUBLIC;
```

Also, in the future, please do include the actual error you received. That helps a lot, and otherwise I would have to guess that what I'm seeing is the same as what you're seeing.

**Comment by loveencounterflow** [comment]
Great, this

```sql
set role dba;
create extension unit;
grant select on unit_units, unit_prefixes to public;
reset role;
```

worked! Thx a lot!

**Comment by ChristophBerg** [comment]
Let's fix this properly within the extension. I wonder why I haven't spotted this before, the problem is so obvious...
