### ISSUE TITLE
Add support for units Offset

### ISSUE THREAD

**Issue by itvieira** [ChristophBerg/postgresql-unit#5]
Hi Christoph,

First of all, many thanks for putting together such a fantastic units library for PostgreSQL!

I would like to suggest the addition of an Offset value to the units definition to support the representation of shifted units such as Celsius and Fahrenheit more naturally.

Many thanks,

Israel

**Comment by ChristophBerg** [comment]
I've been pondering the idea as well, but so far refrained from jumping on it because these two are basically the only units that would need it. Maybe I could special-case them in the parser... I'll keep the idea in mind, thanks for the feedback!

**Comment by itvieira** [comment]
The parse is not a good idea, the offset value would need to be used in the unit operations equations.

Thanks again.

**Comment by ChristophBerg** [comment]
Internally, values are always expressed in base units, so operators do not need any knowledge of the plethora of derived units; conversions only happen on input and output.

I've just had a look at how GNU units is handling non-linear units, and specifically °C and °F, and it's complicated. Namely, the problem is that absolute values and values that express differences need to be treated differently:
```
$ units
Currency exchange rates from www.timegenie.com on 2016-06-21 
2926 units, 109 prefixes, 88 nonlinear units

You have: 20 °C
You want: K
	* 20
	/ 0.05
You have: tempC(20)
You want: K
	* 293.15
	/ 0.0034112229
You have: 20 °C - 15 °C
You want: K
	* 5
	/ 0.2
You have: tempC(20) - tempC(15)
You want: K
	* 5
	/ 0.2
You have: tempC(20) - tempC(15)
You want: °C
	* 5
	/ 0.2
You have: tempC(20) - tempC(15)
You want: tempC
	-268.15
```

Note in particular the first and the last example here: `20 °C` is parsed as 20 K (as if it was a temperature difference), and the actual difference `tempC(20) - tempC(15)` as -268.15°C (which is 5 K). For °F, things are even weirder.

My first idea was to tell the parser to understand that `°C` and `°F` are to be understood as absolute temperature values (in contrast to what GNU units is doing), but then it's still difficult what to do on output; the `'290 K'::unit @ '°C'` case could be handled similarly, but `('20 °C'::unit - '15 °C') @ '°C'` will then horribly fail just like the last GNU units example above.

A solution might be to take a decision on which of the various synonyms (°C, degC, degcelsius, ...) should include the factor+offset on input/output, and which should only include the factor (which is 1 for Celsius). I'll keep pondering.

**Comment by itvieira** [comment]
I believe the problem is being caused by the Minus operator that loses the offset on the result.

C = A - B => C.Offset = A.Offset - B.Offset => 0.0, therefore C @ '°C' = C.Value in K

Likewise, the Plus operator has the inverse effect with C.Offset = A.Offset + B.Offset.

I can see two options:
1. - operations are not supported on Units with Offset != 0.0, conversion only.
2. - operations are carried out on the definition unit, e.g. °C, with the constraint of same dimensions and offset value (A and B in °C), the result (in °C) is converted to the base unit.

The first is probable a simple solution to start with, the second is a more complex solution and would require further analysis to ponder the feasibility of design and implementation.

A = '20 °C'::unit @ '°C'
B = '15 °C'::unit @ '°C'
C = A - B @ '°C' = 278.15 K .'. 5 °C
C = A + B @ '°C' = 308.15 K .'. 35 °C

Hope it makes sense, I'm going to setup a few experiments to further test the idea.
